/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Raquel Rojas
 */
public class detallesVehiculo extends javax.swing.JFrame {

    /**
     * Creates new form detallesVehiculo
     */
    public detallesVehiculo() {
        initComponents();
    }
    
    public void vehiculo(String placa) throws SQLException{
        Conexion cc = new Conexion();
        try {
            ResultSet rs = cc.vehiculo(placa);
            rs.next();
            
            Capacidad.setText(rs.getString("capacidad"));
            MaletasField.setText(rs.getString("capacidadMaletas"));
            PlacaField.setText(placa);
            Puertas.setText(rs.getString("numeroPuertas"));
            Transmision.setText(rs.getString("transmision"));
            mbg.setText(rs.getString("mpg"));
            vin.setText(rs.getString("vin"));
            
            
        }catch (SQLException ex){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Transmision = new javax.swing.JTextField();
        vin = new javax.swing.JTextField();
        MaletasField = new javax.swing.JTextField();
        PlacaField = new javax.swing.JTextField();
        Puertas = new javax.swing.JTextField();
        mbg = new javax.swing.JTextField();
        Capacidad = new javax.swing.JTextField();
        cerrar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Placa:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 57, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Número de puertas:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 150, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Capacidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 172, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Transmisión: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 109, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Maletas:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 55, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Detalles del Vehiculo ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 16, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vin:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 172, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mbg:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 226, -1, -1));

        Transmision.setEditable(false);
        getContentPane().add(Transmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 68, -1));

        vin.setEditable(false);
        getContentPane().add(vin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 47, -1));

        MaletasField.setEditable(false);
        getContentPane().add(MaletasField, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 52, 47, -1));

        PlacaField.setEditable(false);
        getContentPane().add(PlacaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 54, 55, -1));

        Puertas.setEditable(false);
        getContentPane().add(Puertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 106, 51, -1));

        mbg.setEditable(false);
        getContentPane().add(mbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(314, 223, 47, -1));

        Capacidad.setEditable(false);
        getContentPane().add(Capacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 51, -1));

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(0, 0, 153));
        cerrar.setText("Cerrar");
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        getContentPane().add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 293, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Capacidad;
    private javax.swing.JTextField MaletasField;
    private javax.swing.JTextField PlacaField;
    private javax.swing.JTextField Puertas;
    private javax.swing.JTextField Transmision;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField mbg;
    private javax.swing.JTextField vin;
    // End of variables declaration//GEN-END:variables
}
