/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Raquel Rojas
 */
public class DetalleReserva extends javax.swing.JFrame {

    /**
     * Creates new form DetalleReserva
     */
    public DetalleReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reservasFil = new javax.swing.JTable();
        NoReserva = new javax.swing.JTextField();
        idOperador = new javax.swing.JTextField();
        placa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        sede = new javax.swing.JComboBox<>();
        fechaInicio = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Operador:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 136, -1, -1));

        reservasFil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        reservasFil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                reservasFilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(reservasFil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 247, 379, 142));
        getContentPane().add(NoReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 42, 116, -1));

        idOperador.setText("0");
        getContentPane().add(idOperador, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 133, 71, -1));

        placa.setText("0");
        getContentPane().add(placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 203, 90, -1));

        jLabel2.setText("Punto de Recogida:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 136, -1, -1));

        jLabel3.setText("Placa del Vehiculo ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 206, -1, -1));

        jLabel4.setText("Fecha Inicio:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 209, -1, -1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 98, 643, 10));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Filtrar");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 86, -1, -1));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Detalle de Reservar ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 13, -1, -1));

        jLabel5.setText("Número de Reserva:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 45, -1, -1));

        jButton1.setText("Filtrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 170, -1, -1));

        btnVer.setText("Ver detalle");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });
        getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 412, -1, -1));

        sede.setForeground(new java.awt.Color(0, 0, 102));
        sede.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cualquiera", "Aeropuerto Juan Santamaria", "Santa Ana", "Paseo Colon", "Paseo de las flores ", "Curridabat" }));
        getContentPane().add(sede, new org.netbeans.lib.awtextra.AbsoluteConstraints(383, 133, 140, -1));
        getContentPane().add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 203, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        
    }//GEN-LAST:event_btnVerActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int idO = Integer.parseInt(idOperador.getText());
        String plac = placa.getText();
        //java.sql.Date fechaI = new java.sql.Date(fechaInicio.getDate().getTime());
        String sedeRecoger = sede.getSelectedItem().toString();
        
        Conexion cn = new Conexion();
        ResultSet rs = cn.reservaFiltrada(sedeRecoger, plac, idO);
        DefaultTableModel table = new DefaultTableModel();
        this.reservasFil.setModel(table);
        table.setColumnIdentifiers(new Object[]{"Numero Reserva", "idCliente", "Placa","Sede"});
        
        try{
            while(rs.next()){
            table.addRow(new Object[]{rs.getInt("idReserva"), rs.getInt("idCliente"),rs.getString("idVehiculo"),rs.getString("sede")});
            }
        }catch(Exception e){System.out.println("Hubo error" + e);}
        
        JOptionPane.showMessageDialog(null,"");
        
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void reservasFilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reservasFilMouseClicked
        // TODO add your handling code here:
        int selectedRow = reservasFil.getSelectedRow();
        String numR = reservasFil.getModel().getValueAt(selectedRow,0).toString();
        NoReserva.setText(numR);
    }//GEN-LAST:event_reservasFilMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NoReserva;
    private javax.swing.JButton btnVer;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JTextField idOperador;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField placa;
    private javax.swing.JTable reservasFil;
    private javax.swing.JComboBox<String> sede;
    // End of variables declaration//GEN-END:variables
}
