/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Entidades.Licencia;
import Interfaz.MenuPrincipal;
import Operaciones.LicenciaOp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author marip
 */
public class Licencias extends javax.swing.JFrame {

    /**
     * Creates new form Licencia
     */
    public Licencias() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooserFoto = new javax.swing.JFileChooser();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblFechaE = new javax.swing.JLabel();
        txtFechaE = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFechaExp = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        lblTipo = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(chooserFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 0, 10));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Licencia Cliente");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 25, -1, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cédula");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 88, -1, -1));
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 85, 119, -1));

        lblFechaE.setForeground(new java.awt.Color(255, 255, 255));
        lblFechaE.setText("Fecha de Emisión");
        getContentPane().add(lblFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 143, -1, -1));

        txtFechaE.setText("dd/mm/yyyy");
        getContentPane().add(txtFechaE, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 140, 119, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fecha de Expiración");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 187, -1, -1));

        txtFechaExp.setText("dd/mm/yyyy");
        getContentPane().add(txtFechaExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 184, 119, -1));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 109, -1));

        lblTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblTipo.setText("Tipo");
        getContentPane().add(lblTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 242, -1, -1));
        getContentPane().add(txtTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 239, 119, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setForeground(new java.awt.Color(0, 0, 102));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
         if (!txtCedula.getText().isEmpty() & !txtTipo.getText().isEmpty()) {
            Licencia licencia = new Licencia();
        
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        java.util.Date parsed = null;
        try {
            parsed = format.parse(txtFechaE.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ServMantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date fechaE = new java.sql.Date(parsed.getTime());
        
        java.util.Date parsed2 = null;
        try {
            parsed2 = format.parse(txtFechaExp.getText());
        } catch (ParseException ex) {
            Logger.getLogger(ServMantenimiento.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        java.sql.Date fechaExp = new java.sql.Date(parsed2.getTime());
         
        if (fechaE.compareTo(fechaExp) > 0) {
            JOptionPane.showMessageDialog(null, "No puede continuar por que la fecha de expedición no puede ser mayor a la fecha de expiración");
        } else{
        
        
        licencia.setCedula(Integer.parseInt(txtCedula.getText()));
        licencia.setFechaEmision(fechaE);
        licencia.setTipo(txtTipo.getText());
        licencia.setFechaExpiracion(fechaExp);
        
       LicenciaOp.registrarLicencia(licencia);
       JOptionPane.showMessageDialog(null, "La licencia se insertó correctamente");
       
        Clientes cliente = new Clientes();
        cliente.setVisible(true);
        this.setVisible(false);
        }
        } else {
             JOptionPane.showMessageDialog(null, "Por favor llenar todos los campos");
         }


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JFileChooser chooserFoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFechaE;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtFechaE;
    private javax.swing.JTextField txtFechaExp;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables


}
