/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Dell
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarEmpresa = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        registrarServMantenimiento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(0, 0));

        registrarEmpresa.setText("Registrar Empresa");
        registrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpresaActionPerformed(evt);
            }
        });

        registrarCliente.setText("Registrar Cliente");
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });

        registrarServMantenimiento.setText("Registrar Servicio Mantenimiento");
        registrarServMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarServMantenimientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(registrarEmpresa)
                        .addGap(18, 18, 18)
                        .addComponent(registrarCliente))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(registrarServMantenimiento)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(registrarServMantenimiento)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registrarEmpresa)
                    .addComponent(registrarCliente))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpresaActionPerformed
        Empresas emp = new Empresas();
        emp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarEmpresaActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        Clientes cliente = new Clientes();
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void registrarServMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarServMantenimientoActionPerformed
         ServMantenimiento servicio = new ServMantenimiento();
         servicio.setVisible(true);
         this.setVisible(false);
    }//GEN-LAST:event_registrarServMantenimientoActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton registrarCliente;
    private javax.swing.JButton registrarEmpresa;
    private javax.swing.JButton registrarServMantenimiento;
    // End of variables declaration//GEN-END:variables
}
