/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Dell
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarEmpresa = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        registrarServMantenimiento = new javax.swing.JButton();
        btnRegVehiculo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();
        registrarCliente1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        registrarEmpresa.setForeground(new java.awt.Color(0, 0, 102));
        registrarEmpresa.setText("Registrar Empresa");
        registrarEmpresa.setBorderPainted(false);
        registrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(registrarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        registrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        registrarCliente.setForeground(new java.awt.Color(0, 0, 102));
        registrarCliente.setText("Registrar Cliente");
        registrarCliente.setBorderPainted(false);
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        registrarServMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        registrarServMantenimiento.setForeground(new java.awt.Color(0, 0, 102));
        registrarServMantenimiento.setText("Registrar Servicio Mantenimiento");
        registrarServMantenimiento.setBorderPainted(false);
        registrarServMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarServMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(registrarServMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        btnRegVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnRegVehiculo.setForeground(new java.awt.Color(0, 0, 102));
        btnRegVehiculo.setText("Registar Vehiculo");
        btnRegVehiculo.setBorderPainted(false);
        btnRegVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú Principal");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 190, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Registrar Rol de Servicio");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 430));

        registrarCliente1.setBackground(new java.awt.Color(255, 255, 255));
        registrarCliente1.setForeground(new java.awt.Color(0, 0, 102));
        registrarCliente1.setText("Registrar Cliente");
        registrarCliente1.setBorderPainted(false);
        registrarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpresaActionPerformed
        Empresas emp = new Empresas();
        emp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarEmpresaActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
        Clientes cliente = new Clientes();
        cliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void registrarServMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarServMantenimientoActionPerformed
         ServMantenimiento servicio = new ServMantenimiento();
         servicio.setVisible(true);
         this.setVisible(false);
       
         
    }//GEN-LAST:event_registrarServMantenimientoActionPerformed

    private void btnRegVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVehiculoActionPerformed
        Vehiculos vehiculo = new Vehiculos();
        vehiculo.setVisible(true);
        this.setVisible(false);
        
        Filtrar filtrar = new Filtrar();
        filtrar.setVisible(true);
        
    }//GEN-LAST:event_btnRegVehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RolServicio rolserv = new RolServicio();
        rolserv.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void registrarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registrarCliente1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JButton registrarCliente1;
    private javax.swing.JButton registrarEmpresa;
    private javax.swing.JButton registrarServMantenimiento;
    // End of variables declaration//GEN-END:variables
}
