/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

/**
 *
 * @author Dell
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registrarEmpresa = new javax.swing.JButton();
        registrarCliente = new javax.swing.JButton();
        registrarServMantenimiento = new javax.swing.JButton();
        btnRegVehiculo = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnEditarVehiculo = new javax.swing.JButton();
        reservar = new javax.swing.JButton();
        btnRecorrido = new javax.swing.JButton();
        btnDetalleReserva = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registrarEmpresa.setBackground(new java.awt.Color(255, 255, 255));
        registrarEmpresa.setForeground(new java.awt.Color(0, 0, 102));
        registrarEmpresa.setText("Registrar Empresa");
        registrarEmpresa.setBorderPainted(false);
        registrarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarEmpresaActionPerformed(evt);
            }
        });
        getContentPane().add(registrarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        registrarCliente.setBackground(new java.awt.Color(255, 255, 255));
        registrarCliente.setForeground(new java.awt.Color(0, 0, 102));
        registrarCliente.setText("Registrar Cliente");
        registrarCliente.setBorderPainted(false);
        registrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(registrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 160, -1));

        registrarServMantenimiento.setBackground(new java.awt.Color(255, 255, 255));
        registrarServMantenimiento.setForeground(new java.awt.Color(0, 0, 102));
        registrarServMantenimiento.setText("Registrar Servicio Mantenimiento");
        registrarServMantenimiento.setBorderPainted(false);
        registrarServMantenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarServMantenimientoActionPerformed(evt);
            }
        });
        getContentPane().add(registrarServMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, -1, -1));

        btnRegVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnRegVehiculo.setForeground(new java.awt.Color(0, 0, 102));
        btnRegVehiculo.setText("Registar Vehiculo");
        btnRegVehiculo.setBorderPainted(false);
        btnRegVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 160, -1));

        lblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("Menú Principal");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(0, 0, 102));
        jButton1.setText("Registrar Rol de Servicio");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, -1, -1));

        btnEditarVehiculo.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarVehiculo.setForeground(new java.awt.Color(0, 0, 102));
        btnEditarVehiculo.setText("Editar Vehiculo");
        btnEditarVehiculo.setBorderPainted(false);
        btnEditarVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarVehiculoActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditarVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 170, -1));

        reservar.setBackground(new java.awt.Color(255, 255, 255));
        reservar.setForeground(new java.awt.Color(0, 0, 102));
        reservar.setText("Reservar");
        reservar.setBorderPainted(false);
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });
        getContentPane().add(reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 160, -1));

        btnRecorrido.setBackground(new java.awt.Color(255, 255, 255));
        btnRecorrido.setForeground(new java.awt.Color(0, 0, 102));
        btnRecorrido.setText("Recorrido Vehicuo");
        btnRecorrido.setBorderPainted(false);
        getContentPane().add(btnRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 170, -1));

        btnDetalleReserva.setBackground(new java.awt.Color(255, 255, 255));
        btnDetalleReserva.setForeground(new java.awt.Color(0, 0, 102));
        btnDetalleReserva.setText("Detalle Reserva");
        btnDetalleReserva.setBorderPainted(false);
        btnDetalleReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetalleReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetalleReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarEmpresaActionPerformed
        Empresas emp = new Empresas();
        emp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarEmpresaActionPerformed

    private void registrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarClienteActionPerformed
   
        Licencias licencia = new Licencias();
        licencia.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_registrarClienteActionPerformed

    private void registrarServMantenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarServMantenimientoActionPerformed
         ServMantenimiento servicio = new ServMantenimiento();
         servicio.setVisible(true);
         this.setVisible(false);
       
         
    }//GEN-LAST:event_registrarServMantenimientoActionPerformed

    private void btnRegVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegVehiculoActionPerformed
        Vehiculos vehiculo = new Vehiculos();
        vehiculo.setVisible(true);
        this.setVisible(false);
                
    }//GEN-LAST:event_btnRegVehiculoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        RolServicio rolserv = new RolServicio();
        rolserv.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarVehiculoActionPerformed
        EditarVehiculos editar = new EditarVehiculos();
        editar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEditarVehiculoActionPerformed

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
        Reservas reserva = new Reservas();
        reserva.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_reservarActionPerformed

    private void btnDetalleReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetalleReservaActionPerformed
        // TODO add your handling code here:
        DetalleReserva reserva = new DetalleReserva();
        reserva.setVisible(true);
    }//GEN-LAST:event_btnDetalleReservaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalleReserva;
    private javax.swing.JButton btnEditarVehiculo;
    private javax.swing.JButton btnRecorrido;
    private javax.swing.JButton btnRegVehiculo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JButton registrarCliente;
    private javax.swing.JButton registrarEmpresa;
    private javax.swing.JButton registrarServMantenimiento;
    private javax.swing.JButton reservar;
    // End of variables declaration//GEN-END:variables
}
