/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.Conexion;
import static Conexion.Conexion.getConexion;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import Main.Main;

/**
 *
 * @author Raquel Rojas
 */
public class Reservas extends javax.swing.JFrame {
public static int  idClienteR;
  
    /**
     * Creates new form Reserva
     */
    public Reservas() {
        initComponents();
        Connection conexion = getConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cedula = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        validar = new javax.swing.JButton();
        imagen = new javax.swing.JLabel();
        continuar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Reservar Vehiculo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 16, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cédula cliente: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 67, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Completo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Dirección:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 196, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Licencia:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 248, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("email:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 140, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("telefono:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 195, -1, 22));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 117, 492, -1));
        getContentPane().add(cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 64, 67, -1));
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 137, 88, -1));
        getContentPane().add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 193, 93, -1));
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 137, 182, -1));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 193, 83, -1));

        validar.setBackground(new java.awt.Color(255, 255, 255));
        validar.setForeground(new java.awt.Color(0, 0, 102));
        validar.setText("Validar");
        validar.setBorderPainted(false);
        validar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validarActionPerformed(evt);
            }
        });
        getContentPane().add(validar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 63, -1, -1));
        getContentPane().add(imagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 248, 155, 91));

        continuar.setBackground(new java.awt.Color(255, 255, 255));
        continuar.setForeground(new java.awt.Color(0, 0, 102));
        continuar.setText("Continuar");
        continuar.setBorderPainted(false);
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });
        getContentPane().add(continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 296, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 530, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void validarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validarActionPerformed

          if (!cedula.getText().isEmpty()) {
        try {                                        
            
            // TODO add your handling code here:
            Connection conexion = getConexion();
            String ced = cedula.getText();
            String sql = "Select (cedula) from esquema.cliente Where cedula = '"+ced+"'";
            PreparedStatement stmt = conexion.prepareStatement(sql);
            try {
                ResultSet rs = stmt.executeQuery();
                if(Conexion.existeCliente(ced)==0){
                    ResultSet cliente = Conexion.obtenerCliente(ced);
                    cliente.next();
                    direccion.setText(cliente.getString("direccion"));
                    email.setText(cliente.getString("correo"));
                    name.setText(cliente.getString("nombreCompleto"));
                    telefono.setText(cliente.getString("telefono"));
                    Blob foto = cliente.getBlob("fotoLicencia");
                    byte []recu = foto.getBytes(1, (int) foto.length());
                    BufferedImage img = ImageIO.read(new ByteArrayInputStream(recu));
            
            Image imges = img.getScaledInstance(imagen.getWidth(),imagen.getHeight(), Image.SCALE_SMOOTH);
                
            imagen.setIcon(new ImageIcon(imges));
    
                }else{JOptionPane.showMessageDialog(null, "El cliente no existe, por favor registrarlo");}
            } catch (SQLException ex) {
                Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("1");
            } catch (IOException ex) {
                Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
            
          idClienteR = Integer.parseInt(cedula.getText());
        } else  {
            JOptionPane.showMessageDialog(null,"Por favor indique la cedula");
        }
   
        
    }//GEN-LAST:event_validarActionPerformed

    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        try {
            // TODO add your handling code here:
            Connection conexion = getConexion();
            String ced = cedula.getText();
            String sql = "Select (cedula) from esquema.cliente Where cedula = '"+ced+"'";
            PreparedStatement stmt = conexion.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            if(Conexion.existeCliente(ced)==0){
                Filtrar filtrar = new Filtrar();
                filtrar.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "No puede continuar por que el cliente no existe, por favor registrarlo");}
        } catch (SQLException ex) {
            Logger.getLogger(Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_continuarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cedula;
    private javax.swing.JButton continuar;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField email;
    private javax.swing.JLabel imagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField name;
    private javax.swing.JTextField telefono;
    private javax.swing.JButton validar;
    // End of variables declaration//GEN-END:variables
}
