/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Apis.enviarCorreo;
import Entidades.RoldeServicio;
import Operaciones.RolServicioOp;
import Servicios.Password;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class RolServicio extends javax.swing.JFrame {

    /**
     * Creates new form RolServicio
     */
    public RolServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 352, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Indicar direccion de correo electronico para generar usuario y contraseña");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 530, 70));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 0, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    if (!txtCorreo.getText().isEmpty()) {
            String contraseña = String.valueOf(Password.generatePswd());
        enviarCorreo.send(txtCorreo.getText(),"Datos de Usuario", "Usuario: "+txtCorreo.getText()
                +"\n\n"+"Contraseña: "+contraseña,"rentacarkpr@gmail.com", "prograbases1");
        
        RoldeServicio rol = new RoldeServicio();
        rol.setUsuario(txtCorreo.getText());
        rol.setContraseña(contraseña);
        RolServicioOp.registrarRoldeServicio(rol);
        JOptionPane.showMessageDialog(null, "El nuevo rol se insertó correctamente");
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
       } else {
           JOptionPane.showMessageDialog(null, "Por favor llene el espacio");
       }
    }//GEN-LAST:event_btnEnviarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
