/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Apis.enviarCorreo;
import Entidades.RoldeServicio;
import Operaciones.RolServicioOp;
import Servicios.Password;
import java.util.Arrays;
import javax.swing.JOptionPane;
import Entidades.Operador;
import Operaciones.OperadorOp;

/**
 *
 * @author Dell
 */
public class RolServicio extends javax.swing.JFrame {
    
    public static int idOperador = 6;

    /**
     * Creates new form RolServicio
     */
    public RolServicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEnviar = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblTexto = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, -1, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 230, -1));

        lblNombre.setForeground(new java.awt.Color(255, 255, 255));
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, -1, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 240, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registrar Operador");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Correo:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Telefono:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 180, -1));

        lblTexto.setForeground(new java.awt.Color(255, 255, 255));
        lblTexto.setText("Se le enviará al correo su usuario y contraseña");
        getContentPane().add(lblTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
    if (!txtCorreo.getText().isEmpty() & !txtNombre.getText().isEmpty() & !txtTelefono.getText().isEmpty()) {
            String contraseña = String.valueOf(Password.generatePswd());
        enviarCorreo.send(txtCorreo.getText(),"Datos de Usuario", "Usuario: "+txtCorreo.getText()
                +"\n\n"+"Contraseña: "+contraseña,"rentacarkpr@gmail.com", "prograbases1");
        
        RoldeServicio rol = new RoldeServicio();
        rol.setUsuario(txtCorreo.getText());
        rol.setContraseña(contraseña);
        RolServicioOp.registrarRoldeServicio(rol);
        
        Operador operador = new Operador();
        operador.setCedula(idOperador);
        operador.setNombre(txtNombre.getText());
        operador.setCorreo(txtCorreo.getText());
        operador.setTelefono(txtTelefono.getText());
        
        OperadorOp.registrarOperador(operador);
        
        idOperador++;
   
        JOptionPane.showMessageDialog(null, "El nuevo rol se insertó correctamente");
        this.setVisible(false);
        Login login = new Login();
        login.setVisible(true);
       } else {
           JOptionPane.showMessageDialog(null, "Por favor llene el espacio");
       }
    }//GEN-LAST:event_btnEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTexto;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
