/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Entidades.Vehiculo;
import Operaciones.VehiculoOp;
import java.awt.Image;
import java.io.File;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import Interfaz.MenuPrincipal;


/**
 *
 * @author marip
 */
public class Vehiculos extends javax.swing.JFrame {

    public Vehiculos() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        lblVehiculo = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lbllAñoFabricacion = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        lblCapacidad = new javax.swing.JLabel();
        lblFoto2 = new javax.swing.JLabel();
        btnFoto = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtMarca = new javax.swing.JTextField();
        txtCapacidad = new javax.swing.JTextField();
        lblFoto = new javax.swing.JLabel();
        chooserFoto = new javax.swing.JFileChooser();
        lblKilometraje = new javax.swing.JLabel();
        txtKilometraje = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPuertas = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtMillas = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        txtMaletas = new javax.swing.JTextField();
        lblTransmision = new javax.swing.JLabel();
        txtTransmision = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSede = new javax.swing.JTextField();
        lblEstilo = new javax.swing.JLabel();
        txtEstilo = new javax.swing.JTextField();
        lblServicio = new javax.swing.JLabel();
        txtServicio = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVehiculo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblVehiculo.setText("Nuevo Vehiculo");
        getContentPane().add(lblVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 23, -1, -1));

        lblPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaca.setText("Placa");
        getContentPane().add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        lbllAñoFabricacion.setForeground(new java.awt.Color(255, 255, 255));
        lbllAñoFabricacion.setText("Año de Fabricación");
        getContentPane().add(lbllAñoFabricacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));
        getContentPane().add(txtPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 160, -1));
        getContentPane().add(txtAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, -1));

        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setText("Color");
        getContentPane().add(lblColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));
        getContentPane().add(txtColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, -1));

        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca");
        getContentPane().add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, -1));

        lblCapacidad.setForeground(new java.awt.Color(255, 255, 255));
        lblCapacidad.setText("Capacidad");
        getContentPane().add(lblCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        lblFoto2.setForeground(new java.awt.Color(255, 255, 255));
        lblFoto2.setText("Foto Vehiculo");
        getContentPane().add(lblFoto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 611, -1, -1));

        btnFoto.setBackground(new java.awt.Color(255, 255, 255));
        btnFoto.setForeground(new java.awt.Color(0, 0, 102));
        btnFoto.setText("Elegir Foto");
        btnFoto.setBorderPainted(false);
        btnFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoActionPerformed(evt);
            }
        });
        getContentPane().add(btnFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(583, 607, -1, -1));

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setForeground(new java.awt.Color(0, 0, 102));
        btnRegistrar.setText("Registrar Vehiculo");
        btnRegistrar.setBorderPainted(false);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 662, -1, -1));
        getContentPane().add(txtMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 170, -1));
        getContentPane().add(txtCapacidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 166, -1));
        getContentPane().add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 316, 227));
        getContentPane().add(chooserFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 645, 0, 0));

        lblKilometraje.setForeground(new java.awt.Color(255, 255, 255));
        lblKilometraje.setText("Kilometraje");
        getContentPane().add(lblKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        txtKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKilometrajeActionPerformed(evt);
            }
        });
        getContentPane().add(txtKilometraje, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 170, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("numero de Puertas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vin");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 460, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Millas por Galón");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Costo por Dia");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 560, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Capacidad Maletas");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, -1, -1));
        getContentPane().add(txtPuertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 170, -1));
        getContentPane().add(txtVin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 170, -1));
        getContentPane().add(txtMillas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 170, -1));
        getContentPane().add(txtCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 560, 170, -1));
        getContentPane().add(txtMaletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 610, 170, -1));

        lblTransmision.setForeground(new java.awt.Color(255, 255, 255));
        lblTransmision.setText("Transmisión");
        getContentPane().add(lblTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));
        getContentPane().add(txtTransmision, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 150, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sede");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));
        getContentPane().add(txtSede, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, 150, -1));

        lblEstilo.setForeground(new java.awt.Color(255, 255, 255));
        lblEstilo.setText("Estilo");
        getContentPane().add(lblEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, -1, -1));
        getContentPane().add(txtEstilo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 145, -1));

        lblServicio.setForeground(new java.awt.Color(255, 255, 255));
        lblServicio.setText("IdServicio");
        getContentPane().add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, -1, -1));
        getContentPane().add(txtServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 137, -1));

        btnVolver.setBackground(new java.awt.Color(255, 255, 255));
        btnVolver.setForeground(new java.awt.Color(0, 0, 102));
        btnVolver.setText("Volver");
        btnVolver.setBorderPainted(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 660, -1, -1));

        lblFondo.setBackground(new java.awt.Color(0, 0, 102));
        lblFondo.setOpaque(true);
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    File fichero;
    
    private void btnFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoActionPerformed
        int resultado;

        Vehiculos ventana = new Vehiculos();
        
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("JPG y PNG","jpg","png");
        ventana.chooserFoto.setFileFilter(filtro);
        resultado= ventana.chooserFoto.showOpenDialog(null);


if (JFileChooser.APPROVE_OPTION == resultado){


        fichero = ventana.chooserFoto.getSelectedFile();
        try{
               ImageIcon icon = new ImageIcon(fichero.toString());
               Icon icono = new ImageIcon(icon.getImage().getScaledInstance(lblFoto.getWidth(),
                       lblFoto.getHeight(), Image.SCALE_DEFAULT));
               lblFoto.setText(null);
               lblFoto.setIcon( icono );
        }catch(Exception ex){

           JOptionPane.showMessageDialog(null, "Error abriendo la imagen "+ ex);
         
        }
    
 }
    }//GEN-LAST:event_btnFotoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Vehiculo vehiculo = new Vehiculo();
        
        vehiculo.setPlaca(txtPlaca.getText());
        vehiculo.setAñoFabricacion(Integer.parseInt(txtAño.getText()));
        vehiculo.setColor(txtColor.getText());
        vehiculo.setMarca(txtMarca.getText());
        vehiculo.setCapacidad(Integer.parseInt(txtCapacidad.getText()));
        vehiculo.setKilometraje(Integer.parseInt(txtKilometraje.getText()));
        vehiculo.setNumeroPuertas(Integer.parseInt(txtPuertas.getText()));
        vehiculo.setVin(txtVin.getText());
        vehiculo.setMpg(Integer.parseInt(txtMillas.getText()));
        vehiculo.setCostoDia(Integer.parseInt(txtCosto.getText()));
        vehiculo.setCapacidadMaletas(Integer.parseInt(txtMaletas.getText()));
        vehiculo.setTransmision(txtTransmision.getText());
        vehiculo.setSede(txtSede.getText());
        vehiculo.setEstilo(txtEstilo.getText());
        vehiculo.setEstado("Activo");
        vehiculo.setIdServicio(Integer.parseInt(txtServicio.getText()));

        
      VehiculoOp.registrarVehiculo(vehiculo, fichero);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKilometrajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKilometrajeActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
       MenuPrincipal menu = new MenuPrincipal();
       menu.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFoto;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JFileChooser chooserFoto;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCapacidad;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEstilo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JLabel lblKilometraje;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JLabel lblTransmision;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JLabel lbllAñoFabricacion;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCapacidad;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtEstilo;
    private javax.swing.JTextField txtKilometraje;
    private javax.swing.JTextField txtMaletas;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMillas;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtPuertas;
    private javax.swing.JTextField txtSede;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTransmision;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
